In [1]:
import numpy as np
import pandas as pd
import concurrent.futures
import timeit
from functools import partial
from copy import deepcopy
import sys
from IPython.display import display
import os
import pprint
import random
# Add measurement mcts python package to path
sys.path.append('../src/measurement_mcts')
from measurement_mcts.mcts.mcts import mcts_with_rollout
from measurement_mcts.mcts.tree_viz import render_pyvis
from measurement_mcts.state_evaluation.hertg import HERTG
from measurement_mcts.environment.measurement_control_env import MeasurementControlEnvironment
from measurement_mcts.utils.metrics import get_percent_done, save_environment_config, get_mcts_metrics, worker_wrapper

# Create the environment
env = MeasurementControlEnvironment(init_reset=False)

Toy Measurement Control Initialized

/home/austin/.local/lib/python3.10/site-packages/matplotlib/projections/__init__.py:63: UserWarning: Unable to import Axes3D. This may be due to multiple versions of Matplotlib being installed (e.g. as a system package and as a pip package). As a result, the 3D projection is not available.
  warnings.warn("Unable to import Axes3D. This may be due to multiple versions of "

In [3]:
# Save the object configurations to a folder for use in the experiment
num_trials = 100
folder = "trial_configs1"

# Create the folder if it doesn't exist
if not os.path.exists(folder):
    os.makedirs(folder)

for i in range(num_trials):
    env.reset() # Reset the environment to a new random state
    env.save_state(folder, f"trial_{i}") # Save the environment state to a file
    
# Save the environment configuration
save_environment_config(env, folder)

Environment configuration saved to trial_configs1/env_config.txt

In [2]:
# Load the environment state once.
state = env.load_state("trial_configs1", "trial_0")
state = env.get_state()

def run_trial(trial):
    # Create a unique seed using process ID and trial number.
    # seed = os.getpid() + trial
    # np.random.seed(seed)  # Re-seed NumPy's RNG in this process.
    print(f'Running trial {trial}')
    return get_mcts_metrics(env, state, rollout_method="random")

all_results = []
with concurrent.futures.ProcessPoolExecutor() as executor:
    futures = []
    # Schedule a job for each trial.
    for trial in range(200):
        # futures.append(executor.submit(run_trial, trial))
        futures.append(
            executor.submit(
                worker_wrapper,
                trial_number=trial,
                trial_config_name="trial_0",
                rollout_method="random",
                trial_config_path="trial_configs1",
            )
        )
    
    # Gather the results as tasks complete.
    for future in concurrent.futures.as_completed(futures):
        try:
            result = future.result()
            all_results.append(result)
        except Exception as e:
            print("An error occurred during execution:", e)

df = pd.DataFrame(all_results)
display(df)

# Write to file
df.to_csv("same_environment_results_same_random.csv", index=False)

Toy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control Initialized

Toy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         2.05904346 0.         0.        ]
sum_traces: 2.0590434628321783
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0. 16.  0.  0. 16.  0.  0.]
sum_traces: 64.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Toy Measurement Control Initializedsum_traces: 0.0

Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.][0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

sum_traces: 0.0sum_traces: 0.0
Toy Measurement Control Initialized
Toy Measurement Control Initialized

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
[ 0.  0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 32.0
[ 0.  0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 32.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0. 16. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0

,LI,EF,DF,HL,rollout_method,hertg_method,done,percent_done,cumulative_reward,num_actions,computation_time,computation_per_action,trial_config
0,100,0.1,1.0,6,random,static,True,100.000000,6.889964,91,108.052834,1.187394,trial_0
1,100,0.1,1.0,6,random,static,True,100.000000,6.930759,89,116.376976,1.307606,trial_0
2,100,0.1,1.0,6,random,static,True,100.000000,6.918324,93,118.156910,1.270504,trial_0
3,100,0.1,1.0,6,random,static,True,100.000000,6.950000,99,118.197758,1.193917,trial_0
4,100,0.1,1.0,6,random,static,True,100.000000,6.904096,94,118.375477,1.259314,trial_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,100,0.1,1.0,6,random,static,False,91.666667,6.353654,200,150.184470,0.750922,trial_0
196,100,0.1,1.0,6,random,static,False,91.666667,6.370797,200,147.015021,0.735075,trial_0
197,100,0.1,1.0,6,random,static,False,91.666667,6.370797,200,142.247488,0.711237,trial_0
198,100,0.1,1.0,6,random,static,False,91.666667,6.356125,200,134.021646,0.670108,trial_0
199,100,0.1,1.0,6,random,static,False,91.666667,6.349154,200,124.215376,0.621077,trial_0

In [12]:
# Run the same ennvironment multiple times and see if results are the same
state = env.load_state("trial_configs1", "trial_0")
state = env.get_state()
metrics = []
for i in range(5):
    print(f'Running trial {i}')
    metrics.append(get_mcts_metrics(env, state, rollout_method="same"))
    
df = pd.DataFrame(metrics)
display(df)

Running trial 0

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Running trial 1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Running trial 2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Running trial 3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Running trial 4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0

,LI,EF,DF,HL,rollout_method,hertg_method,done,percent_done,cumulative_reward,num_actions,computation_time,computation_per_action
0,100,0.1,1.0,6,same,static,True,100.0,6.950000,96,27.932846,0.290967
1,100,0.1,1.0,6,same,static,True,100.0,6.950000,98,29.409157,0.300093
2,100,0.1,1.0,6,same,static,True,100.0,6.950000,88,27.270899,0.309897
3,100,0.1,1.0,6,same,static,True,100.0,6.949996,91,26.727098,0.293704
4,100,0.1,1.0,6,same,static,True,100.0,6.949966,90,27.009235,0.300103

In [3]:
# Define different experiment configurations
horizon_lengths = [1, 3, 6, 9]

# Path to the directory where trial configurations are stored.
trial_config_path = "trial_configs1"  # Update this path as needed.

In [ ]:
def run_experiments_for_rollout_methods(rollout_methods, trial_config_path, trial_config_names, num_same_config=10, **kwargs):
    """
    For each rollout method, run experiments for every pre-saved trial configuration.
    
    Parameters:
        rollout_methods (list of str): List of rollout methods to test.
        trial_config_path (str): Directory containing the trial configuration files.
        trial_config_names (list of str): List of trial configuration file names (without the .pkl extension).
        kwargs: Additional keyword arguments to pass to the worker_wrapper.
    
    Returns:
        List[dict]: A list of dictionaries with the metrics for each run.
    """
    all_results = []
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures = []
        trial = 0
        # Schedule a job for each combination of rollout method and trial configuration.
        for method in rollout_methods:
            for config_name in trial_config_names:
                for i in range(num_same_config):
                    futures.append(
                        executor.submit(
                            worker_wrapper,
                            trial_number=trial,
                            trial_config_name=config_name,
                            rollout_method=method,
                            trial_config_path=trial_config_path,
                            **kwargs
                        )
                    )
                    trial += 1
        # Gather the results as tasks complete.
        for future in concurrent.futures.as_completed(futures):
            try:
                result = future.result()
                all_results.append(result)
            except Exception as e:
                print("An error occurred during execution:", e)
    return all_results

# Get list of pickle files in folder
trial_config_names = os.listdir(trial_config_path)
trial_config_names = [f for f in trial_config_names if f.endswith('.pkl')]
trial_config_names = [f[:-4] for f in trial_config_names] # Remove .pkl extension

# Pick a random sample of trial configurations to use for the experiments up to number desired
num_environments = 4
trial_config_names = trial_config_names[:num_environments]

rollout_methods = ['random', 'same', 'random_same', 'zero', 'accelerate']

# Run experiments for each rollout method over all the pre-generated configurations.
num_same_config = 50
max_actions = 400
results = run_experiments_for_rollout_methods(
    rollout_methods,
    trial_config_path,
    trial_config_names,
    max_actions=max_actions,
    LI=200,
    EF=0.1,
    DF=1.0,
    hertg_method='static',
    rollout_pre_collision_stop=False,
    num_same_config=num_same_config,
)

# Compile individual run results into a DataFrame and save to a CSV file.
df = pd.DataFrame(results)
print("Individual run metrics:")
print(f'Number of runs: {len(df)}')
display(df.head())
df.to_csv(f"rollout_methods_{len(trial_config_names)}configs_{num_same_config}same_{max_actions}maxactions.csv", index=False)

Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control Initialized

Toy Measurement Control Initialized

Toy Measurement Control InitializedToy Measurement Control Initialized



Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

Toy Measurement Control Initialized
Toy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0. 16.  0.  0.  0.  0. 16.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 32.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0. 16.  0.  0.  0.  0. 16.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 16.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 32.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 16.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0. 16.  0.  0.  0.  0. 16.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 16.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 96.0sum_traces: 16.0
Toy Measurement Control Initialized

Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16.         16.          0.          0.         16.          1.13268293
  0.          4.80297872  0.          0.          0.          0.        ]
sum_traces: 53.935661651934886
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0. 16.  0.  0.  0.  0. 16.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0.  0. 16.  0.  0.  0.  0. 16.]
sum_traces: 48.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.         16.          0.          0.         16.          1.13268293
  0.          4.80297872  0.          0.          0.          0.        ]
sum_traces: 53.935661651934886
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.         16.          0.          0.         16.          1.13268293
  0.          4.80297872  0.          0.          0.          0.        ]
sum_traces: 53.935661651934886
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16.  0.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.         16.          0.          0.         16.         16.
  2.80256953 16.          0.          0.          0.          0.        ]
sum_traces: 82.80256953266598
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0.  0.  0.  0.  0.  0. 16.  0.]
sum_traces: 80.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0.  0.  0.  0.  0.  0. 16.  0.]
sum_traces: 80.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Toy Measurement Control Initializedsum_traces: 0.0

Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0.  0.  0.  0.  0.  0. 16.  0.]
sum_traces: 80.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Toy Measurement Control Initializedsum_traces: 0.0

Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0

,LI,EF,DF,HL,rollout_method,hertg_method,done,percent_done,cumulative_reward,num_actions,computation_time,computation_per_action,rollout_pre_collision_stop,trial_config
0,100,0.1,1.0,6,random,static,True,100.0,6.896334,85,114.637950,1.348682,True,trial_61
1,100,0.1,1.0,6,random,static,True,100.0,6.950000,79,115.321548,1.459766,True,trial_61
2,100,0.1,1.0,6,random,static,True,100.0,6.950000,84,121.256768,1.443533,True,trial_61
3,100,0.1,1.0,6,random,static,True,100.0,6.950000,85,121.737735,1.432209,True,trial_61
4,100,0.1,1.0,6,random,static,True,100.0,6.929608,89,127.209121,1.429316,True,trial_61

In [ ]:
def run_experiments_for_learning_iterations(learning_iterations, trial_config_path, trial_config_names, num_same_config=10, **kwargs):
    """
    For each learning iteration value, run experiments for every pre-saved trial configuration.
    
    Parameters:
        learning_iterations (list of int): List of learning iteration values to test.
        trial_config_path (str): Directory containing the trial configuration files.
        trial_config_names (list of str): List of trial configuration file names (without the .pkl extension).
        kwargs: Additional keyword arguments to pass to the worker_wrapper.
    
    Returns:
        List[dict]: A list of dictionaries with the metrics for each run.
    """
    all_results = []
    with concurrent.futures.ProcessPoolExecutor(max_workers=30) as executor:
        futures = []
        trial = 0
        # Schedule a job for each combination of learning iteration and trial configuration.
        for LI in learning_iterations:
            for config_name in trial_config_names:
                for i in range(num_same_config):
                    futures.append(
                        executor.submit(
                            worker_wrapper,
                            trial_number=trial,
                            trial_config_name=config_name,
                            rollout_method="same",
                            trial_config_path=trial_config_path,
                            LI=LI,
                            **kwargs
                        )
                    )
                    trial += 1
        # Gather the results as tasks complete.
        num_finished = 0
        for future in concurrent.futures.as_completed(futures):
            try:
                result = future.result()
                all_results.append(result)
                num_finished += 1
                print(f'Finished {num_finished} of {len(futures)}')
            except Exception as e:
                print("An error occurred during execution:", e)
    return all_results

# Get list of pickle files in folder
trial_config_names = os.listdir(trial_config_path)
trial_config_names = [f for f in trial_config_names if f.endswith('.pkl')]
trial_config_names = [f[:-4] for f in trial_config_names] # Remove .pkl extension

# Pick a random sample of trial configurations to use for the experiments up to number desired
num_environments = 4
trial_config_names = trial_config_names[:num_environments]
# trial_config_names = random.sample(trial_config_names, num_environments)

# learning_iterations = [50, 100, 200, 400, 600, 800, 1000]
# learning_iterations = [25, 50, 100, 200, 400]
learning_iterations = [50, 100, 400]

# Run experiments for each learning iteration over all the pre-generated configurations.
num_same_config = 20
max_actions = 400
horizon_length = 3
results = run_experiments_for_learning_iterations(
    learning_iterations,
    trial_config_path,
    trial_config_names,
    max_actions=max_actions,
    EF=0.1,
    DF=1.0,
    HL=horizon_length,
    hertg_method='static',
    rollout_pre_collision_stop=False,
    num_same_config=num_same_config,
)

# Compile individual run results into a DataFrame and save to a CSV file.
df = pd.DataFrame(results)

# Save the DataFrame to a CSV file
df.to_csv(f"learning_iterations_{len(trial_config_names)}configs_{num_same_config}same_{horizon_length}hl.csv", index=False)

Toy Measurement Control InitializedToy Measurement Control Initialized

Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized


Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized
Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 1 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 2 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 3 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 4 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 5 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 6 of 1600
Finished 7 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 8 of 1600
Finished 9 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 10 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 11 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 12 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 13 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 14 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 15 of 1600
Finished 16 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 17 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 18 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 19 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 20 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 21 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 22 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 23 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 24 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 25 of 1600
Finished 26 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 27 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 28 of 1600
Finished 29 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 30 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 31 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 32 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 33 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 34 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 35 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 36 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 37 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0Finished 38 of 1600
Finished 39 of 1600

Toy Measurement Control Initialized
Finished 40 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 41 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 42 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 43 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 44 of 1600
Finished 45 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 46 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 47 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 48 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 49 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 50 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 51 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 52 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 53 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 54 of 1600
Finished 55 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 56 of 1600
Finished 57 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 58 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 59 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 60 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 61 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 62 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 63 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 64 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 65 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 66 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 67 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 68 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 69 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Finished 70 of 1600
Finished 71 of 1600
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 72 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 73 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.][16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]

sum_traces: 96.0sum_traces: 96.0

Toy Measurement Control InitializedToy Measurement Control Initialized

Finished 74 of 1600
Finished 75 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 76 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 77 of 1600
Finished 78 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 79 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 80 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 81 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 82 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 83 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 84 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 85 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 86 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 87 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 88 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 89 of 1600
Finished 90 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 91 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 92 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 93 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 94 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 95 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 96 of 1600
Finished 97 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.][16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]

sum_traces: 0.0sum_traces: 96.0

Toy Measurement Control InitializedToy Measurement Control Initialized

Finished 98 of 1600
Finished 99 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 100 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 101 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control InitializedFinished 102 of 1600
Finished 103 of 1600

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Finished 104 of 1600
Finished 105 of 1600
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 106 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 107 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 108 of 1600
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 109 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 110 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 111 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 112 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Finished 113 of 1600
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0
Toy Measurement Control Initialized
Finished 114 of 1600
Finished 115 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 116 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 117 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 118 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 119 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0

Toy Measurement Control Initialized
Finished 120 of 1600
Finished 121 of 1600
Finished 122 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 123 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 124 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 125 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 126 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 127 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 128 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.][0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

sum_traces: 0.0sum_traces: 0.0

Toy Measurement Control InitializedToy Measurement Control Initialized

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 129 of 1600
Finished 130 of 1600
Finished 131 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 132 of 1600
Finished 133 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 134 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 135 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Toy Measurement Control Initialized
sum_traces: 0.0

Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 136 of 1600
Finished 137 of 1600
Finished 138 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.][16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]

sum_traces: 0.0sum_traces: 96.0

Toy Measurement Control InitializedToy Measurement Control Initialized

Finished 139 of 1600
Finished 140 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 141 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 142 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 143 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]Toy Measurement Control Initialized
sum_traces: 0.0

Toy Measurement Control Initialized
Finished 144 of 1600
Finished 145 of 1600
Finished 146 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16. 16. 16.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 96.0Finished 147 of 1600
Finished 148 of 1600

Toy Measurement Control Initialized
Finished 149 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 150 of 1600
Finished 151 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 152 of 1600
Finished 153 of 1600
[ 0.  0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
Finished 154 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 155 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 156 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]Toy Measurement Control Initialized

sum_traces: 0.0
Toy Measurement Control Initialized
Finished 157 of 1600
Finished 158 of 1600
Finished 159 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 160 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 161 of 1600
Finished 162 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control InitializedFinished 163 of 1600
Finished 164 of 1600

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 165 of 1600
Finished 166 of 1600
[ 0.  0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 167 of 1600
Finished 168 of 1600
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
Finished 169 of 1600
[ 0.  0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

In [10]:
hertg = HERTG(env.get_state(), env, 'static')
hertg.reward_scale

0.01

In [ ]:
def run_experiments_for_hertg_method(hertg_methods, trial_config_path, trial_config_names, num_same_config=10, **kwargs):
    """
    For each HERTG method, run experiments for every pre-saved trial configuration.
    
    Parameters:
        hertg_methods (list of str): List of HERTG methods to test.
        trial_config_path (str): Directory containing the trial configuration files.
        trial_config_names (list of str): List of trial configuration file names (without the .pkl extension).
        kwargs: Additional keyword arguments to pass to the worker_wrapper.
    
    Returns:
        List[dict]: A list of dictionaries with the metrics for each run.
    """
    all_results = []
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures = []
        trial = 0
        # Schedule a job for each combination of HERTG method and trial configuration.
        for method in hertg_methods:
            for config_name in trial_config_names:
                for i in range(num_same_config):
                    futures.append(
                        executor.submit(
                            worker_wrapper,
                            trial_number=trial,
                            trial_config_name=config_name,
                            rollout_method="same",
                            hertg_method=method,
                            trial_config_path=trial_config_path,
                            **kwargs
                        )
                    )
                    trial += 1
        # Gather the results as tasks complete.
        for future in concurrent.futures.as_completed(futures):
            try:
                result = future.result()
                all_results.append(result)
            except Exception as e:
                print("An error occurred during execution:", e)
    return all_results

# Get list of pickle files in folder
trial_config_names = os.listdir(trial_config_path)
trial_config_names = [f for f in trial_config_names if f.endswith('.pkl')]
trial_config_names = [f[:-4] for f in trial_config_names] # Remove .pkl extension

# Pick a random sample of trial configurations to use for the experiments up to number desired
num_environments = 4
trial_config_names = trial_config_names[:num_environments]

# Run experiments for each HERTG method over all the pre-generated configurations.
hertg_methods = ['static', 'dynamic']
num_same_config = 40
results = run_experiments_for_hertg_method(
    hertg_methods,
    trial_config_path,
    trial_config_names,
    max_actions=200,
    LI=200,
    EF=0.1,
    DF=1.0,
    rollout_method='same',
    rollout_pre_collision_stop=False,
    num_same_config=num_same_config,
)

# Compile individual run results into a DataFrame and save to a CSV file.
df = pd.DataFrame(results)

# Save to file
df.to_csv(f"hertg_methods_{len(trial_config_names)}configs_{num_same_config}same.csv", index=False)

Toy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized


Toy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

Toy Measurement Control Initialized

Toy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16.  0.  0.  0.  0. 16.  0.  0.  0.  0.  0. 16.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 80.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 80.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 16.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
[ 0.  0.  0.  0.  0.  0. 16.  0.  0. 16.  0.  0.]
sum_traces: 32.0

In [4]:
def run_experiments_for_collision_stop(collision_stop_methods, trial_config_path, trial_config_names, num_same_config=10, **kwargs):
    """
    For each collision stop method, run experiments for every pre-saved trial configuration.
    
    Parameters:
        collision_stop_methods (list of str): List of collision stop methods to test.
        trial_config_path (str): Directory containing the trial configuration files.
        trial_config_names (list of str): List of trial configuration file names (without the .pkl extension).
        kwargs: Additional keyword arguments to pass to the worker_wrapper.
    
    Returns:
        List[dict]: A list of dictionaries with the metrics for each run.
    """
    all_results = []
    with concurrent.futures.ProcessPoolExecutor() as executor:
        futures = []
        trial = 0
        # Schedule a job for each combination of collision stop method and trial configuration.
        for method in collision_stop_methods:
            for config_name in trial_config_names:
                for i in range(num_same_config):
                    futures.append(
                        executor.submit(
                            worker_wrapper,
                            trial_number=trial,
                            trial_config_name=config_name,
                            rollout_pre_collision_stop=method,
                            trial_config_path=trial_config_path,
                            **kwargs
                        )
                    )
                    trial += 1
        # Gather the results as tasks complete.
        for future in concurrent.futures.as_completed(futures):
            try:
                result = future.result()
                all_results.append(result)
            except Exception as e:
                print("An error occurred during execution:", e)
    return all_results

# Get list of pickle files in folder
trial_config_names = os.listdir(trial_config_path)
trial_config_names = [f for f in trial_config_names if f.endswith('.pkl')]
trial_config_names = [f[:-4] for f in trial_config_names] # Remove .pkl extension

# Pick a random sample of trial configurations to use for the experiments up to number desired
num_environments = 10
trial_config_names = random.sample(trial_config_names, num_environments)

# Run experiments for each collision stop method over all the pre-generated configurations.
pre_collision_stop_methods = [True, False]
num_same_config = 10
results = run_experiments_for_collision_stop(
    pre_collision_stop_methods,
    trial_config_path,
    trial_config_names,
    max_actions=200,
    LI=100,
    EF=0.1,
    DF=1.0,
    rollout_method='same',
    hertg_method='static',
    num_same_config=num_same_config,
)

# Compile individual run results into a DataFrame and save to a CSV file.
df = pd.DataFrame(results)

# Save to file
df.to_csv(f"pre_collision_stop_{len(trial_config_names)}configs_{num_same_config}same.csv", index=False)

Toy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized
Toy Measurement Control Initialized
Toy Measurement Control Initialized
Toy Measurement Control Initialized
Toy Measurement Control InitializedToy Measurement Control Initialized


Toy Measurement Control InitializedToy Measurement Control Initialized

Toy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control InitializedToy Measurement Control InitializedToy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

Toy Measurement Control Initialized

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)
/home/austin/MeasurementMCTS/metrics/../src/measurement_mcts/measurement_mcts/mcts/mcts.py:222: RuntimeWarning: divide by zero encountered in log
  * np.sqrt(np.log(self.number_visits)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0. 16.  0.  0. 16.  0.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0. 16.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0. 16.  0.  0.  0.  0. 16.  0.  0.]
sum_traces: 48.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]sum_traces: 0.0
sum_traces: 0.0
Toy Measurement Control Initialized

Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0. 16.  0.  0.  0. 16.  0.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[16. 16. 16. 16. 16. 16. 16. 16.  0.  0.  0.  0.]
sum_traces: 128.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.][0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

sum_traces: 0.0sum_traces: 0.0
Toy Measurement Control Initialized
Toy Measurement Control Initialized

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0. 16.  0.  0.  0.]
sum_traces: 32.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0.         1.50984962 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.        ]
sum_traces: 1.5098496164500848
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[ 0.  0.  0.  0.  0. 16.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[ 0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
Toy Measurement Control Initialized
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.][0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0

sum_traces: 0.0
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[ 0.  0. 16.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
sum_traces: 16.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sum_traces: 0.0